/**
 * Agent instance creation
 */
import { Experimental_Agent as Agent, stepCountIs } from 'ai';
import type { LanguageModel } from 'ai';
import * as crypto from 'crypto';
import type { createToolRegistry } from './tools';
import type { AgentConfig } from './types/router';
import type { SessionData } from './session-store';
import { sessionStore } from './session-store';
import { SystemContext } from './context/system-context';
import { logTelemetry, getLangfuseTraceId } from './utils/telemetry';

/**
 * Create agent instance with proper configuration
 */
export function createAgentInstance<T extends ReturnType<typeof createToolRegistry>>(
  model: LanguageModel,
  config: AgentConfig<T>,
  sessionId: string,
  tools: T,
  currentSession: SessionData | undefined,
  systemContext?: SystemContext,
): Agent<T> {
  const langfuseTraceId = getLangfuseTraceId(sessionId, config.role);

  const agentConfig = {
    model,
    instructions: config.instructions,
    tools,
    stopWhen: config.stopWhen || [stepCountIs(config.maxSteps)],
    ...(config.prepareStep ? { prepareStep: config.prepareStep } : {}),
    ...(langfuseTraceId
      ? {
          experimental_telemetry: {
            isEnabled: true,
            functionId: config.role,
            metadata: {
              langfuseTraceId,
              sessionId,
              agentRole: config.role,
            },
          },
        }
      : {}),
    onStepFinish: (step: unknown) => {
      // Log telemetry - cast step to access properties
      const stepResult = step as {
        toolCalls?: Array<{ toolName: string; args: unknown }>;
        toolResults?: Array<{ toolName: string; output: unknown }>;
      };

      // Increment step in context
      if (systemContext) {
        systemContext.incrementStep();
      }

      // Log telemetry and send tool call annotations
      if (stepResult.toolCalls) {
        for (const toolCall of stepResult.toolCalls) {
          logTelemetry({
            sessionId,
            timestamp: Date.now(),
            event: 'tool_call',
            toolName: toolCall.toolName as string,
          });

          // Track tool call in context
          if (systemContext) {
            systemContext.reportToolCall(toolCall.toolName as string, config.role, true);
          }
        }
      }

      if (stepResult.toolResults) {
        for (const toolResult of stepResult.toolResults) {
          logTelemetry({
            sessionId,
            timestamp: Date.now(),
            event: 'tool_result',
            toolName: toolResult.toolName as string,
          });

          // Track tool call in context
          if (systemContext) {
            const hasError = toolResult.output && typeof toolResult.output === 'object' && 'error' in toolResult.output;
            systemContext.reportToolCall(
              toolResult.toolName as string,
              config.role,
              !hasError,
              hasError ? String((toolResult.output as { error?: string }).error) : undefined,
            );
          }

          // Extract proposal from writeConfigDraft result
          if (toolResult.toolName === 'writeConfigDraft' && config.role === 'config-engineer') {
            const result = toolResult.output as {
              content?: string;
              checksum?: string;
              valid?: boolean;
            };
            if (result?.content && result?.checksum) {
              const latestProposal = currentSession?.proposals[currentSession.proposals.length - 1];
              if (!latestProposal || latestProposal.checksum !== result.checksum) {
                sessionStore.addProposal(sessionId, {
                  content: result.content,
                  rationale: 'Generated by Config Engineer agent',
                  checksum: result.checksum,
                });
              }
            }
          }

          // Extract proposal from applyConfigPreview result (config content is in the tool call args)
          if (toolResult.toolName === 'applyConfigPreview' && config.role === 'config-engineer') {
            const result = toolResult.output as {
              configValid?: boolean;
              errors?: string[];
            };
            // Find the tool call that invoked this to get the config content
            if (stepResult.toolCalls) {
              for (const toolCall of stepResult.toolCalls) {
                if (toolCall.toolName === 'applyConfigPreview') {
                  const args = toolCall.args as { content?: string };
                  if (args?.content && result?.configValid) {
                    const checksum = crypto.createHash('md5').update(args.content).digest('hex');
                    const latestProposal = currentSession?.proposals[currentSession.proposals.length - 1];
                    if (!latestProposal || latestProposal.checksum !== checksum) {
                      sessionStore.addProposal(sessionId, {
                        content: args.content,
                        rationale: 'Generated and validated by Config Engineer agent',
                        checksum,
                      });
                    }
                  }
                  break;
                }
              }
            }
          }

          // Extract proposal from writeConfig result (config was written to disk)
          if (toolResult.toolName === 'writeConfig' && config.role === 'config-engineer') {
            const result = toolResult.output as {
              ok?: boolean;
              checksum?: string;
              path?: string;
            };
            // Find the tool call that invoked this to get the config content
            if (stepResult.toolCalls) {
              for (const toolCall of stepResult.toolCalls) {
                if (toolCall.toolName === 'writeConfig') {
                  const args = toolCall.args as { content?: string };
                  if (args?.content && result?.ok && result?.checksum) {
                    const latestProposal = currentSession?.proposals[currentSession.proposals.length - 1];
                    if (!latestProposal || latestProposal.checksum !== result.checksum) {
                      sessionStore.addProposal(sessionId, {
                        content: args.content,
                        rationale: 'Generated, validated, and written to disk by Config Engineer agent',
                        checksum: result.checksum,
                      });
                    }
                  }
                  break;
                }
              }
            }
          }
        }
      }
    },
  };

  return new Agent(agentConfig as any) as unknown as Agent<T>;
}

